package com.crbt.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF413CBD)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6764E4)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF5A598B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0CEFF)
val onSecondaryContainerLight = Color(0xFF3A3968)
val tertiaryLight = Color(0xFF805535)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFCDAC)
val onTertiaryContainerLight = Color(0xFF5E381B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1B23)
val surfaceLight = Color(0xFFFCF8FF)
val onSurfaceLight = Color(0xFF1B1B23)
val surfaceVariantLight = Color(0xFFE3E0F2)
val onSurfaceVariantLight = Color(0xFF464554)
val outlineLight = Color(0xFF777585)
val outlineVariantLight = Color(0xFFC7C4D6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF302F38)
val inverseOnSurfaceLight = Color(0xFFF3EFFA)
val inversePrimaryLight = Color(0xFFC2C1FF)
val surfaceDimLight = Color(0xFFDCD8E3)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F2FD)
val surfaceContainerLight = Color(0xFFF0ECF7)
val surfaceContainerHighLight = Color(0xFFEAE6F2)
val surfaceContainerHighestLight = Color(0xFFE4E1EC)


val surfaceLightMediumContrast = Color(0xFFF9F9FF)


val primaryDark = Color(0xFFC2C1FF)
val onPrimaryDark = Color(0xFF1D0B9E)
val primaryContainerDark = Color(0xFF6764E4)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFC3C1F9)
val onSecondaryDark = Color(0xFF2C2B59)
val secondaryContainerDark = Color(0xFF3B3B6A)
val onSecondaryContainerDark = Color(0xFFD3D1FF)
val tertiaryDark = Color(0xFFFFF5F1)
val onTertiaryDark = Color(0xFF4A280C)
val tertiaryContainerDark = Color(0xFFFAC19A)
val onTertiaryContainerDark = Color(0xFF563215)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF13131A)
val onBackgroundDark = Color(0xFFE4E1EC)
val surfaceDark = Color(0xFF13131A)
val onSurfaceDark = Color(0xFFE4E1EC)
val surfaceVariantDark = Color(0xFF464554)
val onSurfaceVariantDark = Color(0xFFC7C4D6)
val outlineDark = Color(0xFF918F9F)
val outlineVariantDark = Color(0xFF464554)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1EC)
val inverseOnSurfaceDark = Color(0xFF302F38)
val inversePrimaryDark = Color(0xFF504CCC)
val surfaceDimDark = Color(0xFF13131A)
val surfaceBrightDark = Color(0xFF393841)
val surfaceContainerLowestDark = Color(0xFF0E0D15)
val surfaceContainerLowDark = Color(0xFF1B1B23)
val surfaceContainerDark = Color(0xFF1F1F27)
val surfaceContainerHighDark = Color(0xFF2A2931)
val surfaceContainerHighestDark = Color(0xFF35343C)




val warningLight = Color(0xFF765B00)
val onWarningLight = Color(0xFFFFFFFF)
val warningContainerLight = Color(0xFFFEC713)
val onWarningContainerLight = Color(0xFF4B3900)
val successLight = Color(0xFF006E29)
val onSuccessLight = Color(0xFFFFFFFF)
val successContainerLight = Color(0xFF2ED25D)
val onSuccessContainerLight = Color(0xFF00330F)

val warningLightMediumContrast = Color(0xFF544000)
val onWarningLightMediumContrast = Color(0xFFFFFFFF)
val warningContainerLightMediumContrast = Color(0xFF917000)
val onWarningContainerLightMediumContrast = Color(0xFFFFFFFF)
val successLightMediumContrast = Color(0xFF004E1B)
val onSuccessLightMediumContrast = Color(0xFFFFFFFF)
val successContainerLightMediumContrast = Color(0xFF008734)
val onSuccessContainerLightMediumContrast = Color(0xFFFFFFFF)

val warningLightHighContrast = Color(0xFF2D2000)
val onWarningLightHighContrast = Color(0xFFFFFFFF)
val warningContainerLightHighContrast = Color(0xFF544000)
val onWarningContainerLightHighContrast = Color(0xFFFFFFFF)
val successLightHighContrast = Color(0xFF00290A)
val onSuccessLightHighContrast = Color(0xFFFFFFFF)
val successContainerLightHighContrast = Color(0xFF004E1B)
val onSuccessContainerLightHighContrast = Color(0xFFFFFFFF)

val warningDark = Color(0xFFFFEBBF)
val onWarningDark = Color(0xFF3E2E00)
val warningContainerDark = Color(0xFFF0BB00)
val onWarningContainerDark = Color(0xFF413100)
val successDark = Color(0xFF4CE870)
val onSuccessDark = Color(0xFF003912)
val successContainerDark = Color(0xFF00BD4C)
val onSuccessContainerDark = Color(0xFF001E06)

val warningDarkMediumContrast = Color(0xFFFFEBBF)
val onWarningDarkMediumContrast = Color(0xFF3E2E00)
val warningContainerDarkMediumContrast = Color(0xFFF0BB00)
val onWarningContainerDarkMediumContrast = Color(0xFF100A00)
val successDarkMediumContrast = Color(0xFF4CE870)
val onSuccessDarkMediumContrast = Color(0xFF001E06)
val successContainerDarkMediumContrast = Color(0xFF00BD4C)
val onSuccessContainerDarkMediumContrast = Color(0xFF000000)

val warningDarkHighContrast = Color(0xFFFFFAF6)
val onWarningDarkHighContrast = Color(0xFF000000)
val warningContainerDarkHighContrast = Color(0xFFFAC309)
val onWarningContainerDarkHighContrast = Color(0xFF000000)
val successDarkHighContrast = Color(0xFFF0FFEB)
val onSuccessDarkHighContrast = Color(0xFF000000)
val successContainerDarkHighContrast = Color(0xFF4AE66F)
val onSuccessContainerDarkHighContrast = Color(0xFF000000)